const sweetsTitle = [
    "Beginning the day with something sweet.",
    "Always save room for dessert.",
    "Dessert is always the solution to any problem.",
    "Hungry? Why wait? Grab a sweet treat!",
    "Keep calm and eat dessert.",
    "Life without sweet treats is no life at all!",
    "So many kinds of desserts, so little time.",
    "Stressed read backward is desserts.",
    "Sweet dreams are made of this.",
    "A bite of deliciousness.",
    "Enjoy the little things.",
    "Happiness starts here.",
    "Baked happiness.",
    "Love at first bite.",
    "Making sweet things happen.",
    "Made for sweet dreams.",
    "Continuous small treats are the secret to happiness.",
    "In the presence of desserts, stress and pressure don’t exist.",
    "You are what you eat, so eat something sweet.",
    "Have you ever tasted heaven?",
    "It’s so hard to stay sad when you’re eating dessert.",
    "Every bite makes you fall in love",
    "There is nothing dessert can’t solve.",
    "Life is better with dessert.",
    "Nothing smells home like the smell of baking",
    "Life is too short to eat boring food.",
    "Dessert is a necessity of life.",
    "Love at first sight? More like love at first bite.",
    "Life is short make it sweet.",
    "Dessert is a necessity of life.",
    "It's the finale. It's the last impression. A bad dessert can ruin the meal.",
];

export default sweetsTitle;